spring:
  name: book-client
  h2:
    console:
      enabled: true
      path: /h2
  main:
    banner-mode: "off"
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  http.converters.preferred-json-mapper: jackson
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false  
  thymeleaf:
    cache: false         

server:
  port: 9000
          
database:
    url: jdbc:h2:mem:client;DB_CLOSE_DELAY=-1
    user: sa
    password: 
    
endpoint.api-livros: http://localhost:8080/api/v2/livros
endpoint.oauth-token: http://localhost:8080/oauth/token
  
oauth.client-id: cliente-app
oauth.client-secret: 123456 