## define se vai utilizar a solução onde authorization server e resource server estão juntos ou separados
## definir como true, significa que o oauth provider está todo configurado aqui na aplicação bookserver
## definir como false, significa que essa aplicação só possui configuração para o resource server
## -> quando está como false, para validar o token é preciso que o authorization server esteja salvando os dados do
## -> client details em um banco de dados (ao invés de em memória).
oauth:
  enabled: true
  all-in-one: true

spring:
  name: book-server
  h2:
    console:
      enabled: true
      path: /h2
  main:
    banner-mode: "off"           
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop      

server:
  port: 8080
          
database:
    url: jdbc:h2:mem:oauth;DB_CLOSE_DELAY=-1
    user: sa
    password: 